name = "backend"
compatibility_date = "2024-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19MZGxjZkRjZDJUMWFPRFNLUjhnM2YiLCJhcGlfa2V5IjoiMDFLMFFWWjZEVkhTRERaUTRIQVFQQjdXWkEiLCJ0ZW5hbnRfaWQiOiIzNGI1MmE1MzE1YTQzMDVlZWRlZGNkYzIxOWI4MGVjNzM0NGMxZDljZjVjNDBlNmNiZmQ1ODlmZGFiNTQ4NDAyIiwiaW50ZXJuYWxfc2VjcmV0IjoiOWMyZjE2NzMtNDU1YS00YTYwLWFlN2EtMTVlOWVhMjY0MTIwIn0.gwfqsN-pK5XKHLmfZRO6G29MYv7aKg2xLd9j5V-Pzq0"

JWT_SECRET = "mySecJwtPassword"
main = "src/index.ts"
